# # Make a list of Groceries that you want to buy.

# list1=["rice","vegetable","dal",]
# # list1.pop(2)
# print(list1)

# name=["saumya","mahi","jija","fatima","bauua"]
# print(name)
# print(type(name))

# banks_list = ["Kotak", "HDFC", "RBL", "SBI", "Bank of Baroda"]
# print(banks_list)
# print(type(banks_list))

# marks_list=[56,65,34,78,91,62]
# print(marks_list)
# print(type(marks_list))

# temperature_list = [21.1, 24.3,8,20]
# print(temperature_list)
# print(type(temperature_list))

# mixed_list=[4,"jija",9.0,"saumya"]
# print(mixed_list)
# print(type(mixed_list))

# names_list = ["annu", "shivam", "deepa", "pooja", "rupa"]
# print (names_list[1])

# names_list = ["annu", "shivam", "deepa", "pooja", "rupa"]
# print (names_list[0]) # se "annu" print hoga
# print (names_list[4])# se "rupa" print hoga
# print (names_list[5])

# names_list = "abhishek"
# print (names_list)

# names_list = ["annu", "shivam", "deepa", "pooja", "rupa"]
# print (len(names_list))

# names_list=["S",4,"R",7,"B"]
# names_list.append("dhruv")
# print ("length of the list is ", len(names_list))
# print (names_list)

# name=["SAUMYA"]
# name.append("savita")
# print(name)
# print("length of the list is",len(name))



# names_list=["shivam","arjun","rishi"]
# print ("length of the list is ", len(names_list))
# names_list.append("alok")
# print ("length of the list is ", len(names_list))
# print (names_list)

# name=["annu","fatima","bauua","mahi","anshuman"]
# name.pop()
# print ("length of the list is ", len(name))
# print(name)

# names_list=["s","a","b","c","d"]
# print ( len(names_list))
# names_list.pop(2)
# print ( len(names_list))
# names_list.pop(2)
# print ("length of the list is ", len(names_list))

# name_list=["anshuman","shivam"]
# if "anshuman" in name_list:
#     if "shivam" in name_list:
#         print("yes","anshuman","shivam" in name_list)

# names_list=["shiv","anshuman","shivam","fatima","bauua"]
# if "shivam" in names_list:
#     print ("Shivam ka naam names_list mei hai:")
# else:
#     print ("Shivam ka naam names_list mei nahi hai:")

# students_list = ["robin", "anamika", "faisal", "valmiki", "waseem", "amara"]

# students_list = ["bauua", "fatima", "anshuman", "aarti", "sandhya", "arav"]
# list_length = len(students_list)
# index = 0
# while index < list_length:
#     print (students_list[index])
#     index = index + 1

# students_name = ["bauua", "fatima", "anshuman", "aarti", "sandhya", "arav"]
# new_list = len(students_name)
# index = 0
# while index < new_list:
#     print (students_name)
#     index+=1

# student_marks = [23, 45, 89, 90, 56, 97, 56, 79, 53, 62, 80] 
# length = len(student_marks)
# index = 0
# total_marks = 0
# while index < len(student_marks):
#     total_marks = student_marks[index] + total_marks
#     index = index + 1
# print ("Total Marks:",(total_marks))

# student_marks = [23, 45, 67, 89, 90, 54, 34, 21, 34, 23, 19, 28, 10, 45, 86, 87, 9]
# list_length = len(student_marks)
# index = 0
# less_than50 = 0
# more_than50 = 0
# while index < list_length:
#     marks = student_marks[index]
#     if marks < 50:
#         less_than50 = less_than50 + 1
#     else:
#         more_than50 = more_than50 + 1
#     index = index + 1
# print ("Marks more than 50: " + str(more_than50))
# print ("Marks less than 50: " + str(less_than50))


   
      

